name: remote_data_kit
description: Un paquete reutilizable para el consumo de APIs usando Dio con manejo de errores centralizado.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ^3.12.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

